### PR TITLE
Semi colons

### PR DESCRIPTION
**Pull request by mchapman**
Had a problem with the missing semi-colons (the file that got concatenated after didn't have the defensive strategy of a semi-colon at the top).

### CODE REVIEW

**Comment by harrastia** [comment]
It would be nice to get this in. I actually spent 1 hour+ today debugging why rrule makes my bundled build break. This was the reason. Any way to retrigger the test run? These changes should be totally harmless.

**Comment by zeiphon** [comment]
Looks like the tests are failing because
```
Use JavaScript Standard Style
/home/travis/build/jkbrzt/rrule/lib/nlp.js:987:4: Extra semicolon.
/home/travis/build/jkbrzt/rrule/lib/rrule.js:2278:4: Extra semicolon.
```
Brilliant.

I, too, spent far too long debugging a bundling issue caused by the lack of trailing semicolons.

**Comment by balazsnemeth** [comment]
Would be great to merge this @jakubroztocil

**Comment by arolson101** [comment]
Try adding ```// eslint-disable-line``` to the line

**Comment by mchapman** [comment]
Superseded by #195

**Pull request closed without merging**
