### PR TITLE
Change precommit to "yarn lint"

### PR DESCRIPTION
**Pull request by epicfaace**
---

This just helps with committing -- otherwise commits take a pretty long time when everything is actually built. I don't think we need to have `yarn build` running after every commit given that there's already CI set up.

### Thanks for contributing to `rrule`!

To submit a pull request, please verify that you have done the following:

- [ ] Merged in or rebased on the latest `master` commit
- [ ] Linked to an existing bug or issue describing the bug or feature you're
      addressing
- [ ] Written one or more tests showing that your change works as advertised

### CODE REVIEW

**Comment by davidgoli** [comment]
Please revert https://github.com/jakubroztocil/rrule/pull/348 as part of this. Thanks!

**Comment by epicfaace** [comment]
@davidgoli are you sure we need to revert that? I believe the line removed in #348 was meant for the single reason that _dist files were checked in to the repo_. Since there's already a CI process, no need to build everything client-side.

Perhaps we can add a line at the bottom of the PR example saying "I have run `yarn test`" or something -- would that work instead?

**Comment by davidgoli** [comment]
@epicfaace You're right, I was mistaken. I think the CI build check should cover running tests/the build step.

**Comment by davidgoli** [comment]
I'd also like to move this project away from the deprecated `tslint` towards `eslint` + the typescript plugin, but that can happen in another PR.

**Pull request merged**
