### PR TITLE
Use separate index file to fix issue with browserify external bundles

### PR DESCRIPTION
**Pull request by SystemParadox**
Fix for invalid paths when putting rrule in an external bundle with `browserify -r`. See  https://github.com/substack/node-browserify/issues/1070.

Without this fix, the following results in an error:

```
npm install rrule
browserify -r rrule -o test.js
# trigger module load
echo 'require("foo");' >> test.js
node test.js
```

```
Error: Cannot find module '..'
```

The error is from `lib/nlp.js`, which is trying to require `./rrule` (`lib/rrule`). However, due to the `main` definition in `package.json`, browserify has already re-aliased this file.

It's a bug with browserify, but I'm not sure when it will be fixed. This is the only module I am using which is subject to this bug at the moment so it would be nice to make this minor change to fix it!

Thanks.

### CODE REVIEW

**Comment by arolson101** [comment]
Hi!  I'm trying to clear out bugs and PRs.  If this PR is still wanted/relevant, please comment and/or fix the conflicts!

**Comment by SystemParadox** [comment]
That should be good to merge now. Thanks!

**Comment by arolson101** [comment]
can you fix tests?

**Comment by davidgoli** [comment]
@SystemParadox are you still working on this?

**Comment by SystemParadox** [comment]
We've switched to webpack which doesn't have this problem so I'm just going to close this now.

**Pull request closed without merging**
