### PR TITLE
Fix DST bugs

### PR DESCRIPTION
**Pull request by davidgoli**
Addresses #233 . Note this removes the requirement to run tests in UTC - now all dates/times are treated as though they are in UTC, even if the host system is not. Previously, dates in local time zones were inconsistent, which is why #219 would repro when the test suite was not run in UTC. I believe this is what most clients will want, most of the time. In this branch, if you give options such as `dtstart` in local time, it will be converted into UTC first. I think this behavior could use more specification - if some of the input times passed to `dtstart`, `until`, or `between` are not in UTC, but others are, what should the behavior be? I believe that's not addressed well in the existing codebase and outside the scope of this fix.

According to the RFC (https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html), there does exist a "timezone" spec like `DTSTART;TZID=America/New_York:19970902T090000`. However, no such support for parsing, storing, or otherwise using such timezones exists in this codebase.

Additionally see https://www.ietf.org/rfc/rfc2445.txt:

>    The use of local time in a DATE-TIME value without the TZID property
>    parameter is to be interpreted as floating time, regardless of the
>    existence of "VTIMEZONE" calendar components in the iCalendar object.

Since this library does not currently support the `TZID` property, all times should be interpreted as "floating" times.

### CODE REVIEW

**Comment by circlingthesun** [comment]
Thanks for all the effort in maintaining this. I really like typescript support.

I've not experienced any timezone issues in the past. This PR however completely changes the way dates are interpreted, and resulted in some code breaking in my case. I've made some adjustments after finding this PR and everything appears to be fine again. It might be worth bumping the major version to reflect this.

Interpreting JS Date object as UTC time makes a lot of sense. However, it makes using rrule with JS Date objects pretty confusing. If I'm dealing with an appointment that occurs monthly in local time, I would expect to write something like this:

```js
new rrule.RRule({
  freq: RRule.MONTHLY,
  dtstart: new Date(2018, 1, 1, 10, 30),
  until: new Date(2018, 12, 31)
}).all()
```
People in Zurich would see:

```
Thu Feb 01 2018 10:30:00 GMT+0100 (Central European Standard Time)
Thu Mar 01 2018 10:30:00 GMT+0100 (Central European Standard Time)
Sun Apr 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Tue May 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Fri Jun 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Sun Jul 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Wed Aug 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Sat Sep 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Mon Oct 01 2018 11:30:00 GMT+0200 (Central European Summer Time)
Thu Nov 01 2018 10:30:00 GMT+0100 (Central European Standard Time)
Sat Dec 01 2018 10:30:00 GMT+0100 (Central European Standard Time)
Tue Jan 01 2019 10:30:00 GMT+0100 (Central European Standard Time)
```
So instead I have to interpret local time as UTC, run the recurrence, then reinterpret the resukt as local time. Once you've figured it out it makes sense, however, it's not ideal. Especially when you console.log your results and you see the wrong local representation.

Perhaps it's better to deprecate Date objects and just use UNIX time or ISO 8601 date strings to reduce confusion?

**Comment by davidgoli** [comment]
@circlingthesun Thanks for your input on this. As it happens, I'm currently working with some colleagues on an implementation of the RFC timezone. I would contend that the change in this branch makes the behavior conform more closely to the RFC. As you say, though, this is a breaking change and probably warrants a major version. I'm strongly considering making Luxon a peer dependency of this project, as it has robust international timezone support and is probably the best-in-class date library and also behaves much more like Python's datetime class, including support for both "naive" and timezone-aware dates. A robust implementation of non-UTC timezones is going to require some sort of library that's more functional than the built-in JS Date. However, it's really nice to have a library that has no dependencies, and of course different people will have different opinions on their preferred Date implementation.

As far as your code, thanks for bringing this up, we really need to update the docs. You _will_ get the correct result if you rewrite your code as follows:

```js
new rrule.RRule({
  freq: RRule.MONTHLY,
  dtstart: new Date(Date.UTC(2018, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2018, 12, 31))
}).all()
```

Numerous tests in the test suite verify identical results across a variety of timezones. However, as you've pointed out, this is a breaking change even though I had been thinking of it as a bugfix. I'm already hoping 3.0 will introduce robust timezone awareness via a `TZID` param, but arguably the 2.3.x series could already be 3.0 and the `TZID` work could be 4.0. We don't have a lot of active contributors right now so I'd be open for discussion on this.

**Comment by arolson101** [comment]
+1 for luxon

**Comment by circlingthesun** [comment]
@davidgoli, thanks for the thoughtful reply. I don't actually use Date objects in my own code. I just convert my dates to Date objects for use with rrule. I mostly use ISO 8601 date strings. It allows me to not worry about serialization, while still being human readable and comparable (if the same timezone is used). I convert them to moment objects when need be. I'd like to eventually replace moment with luxon. I still need to have a look at browser support though.

It would probably be better for rrule to not be opinionated about what date library you use. If not, think luxon would probably not be a bad choice. It's certainly much smaller than moment-timezone.

**Comment by SystemParadox** [comment]
This change makes a lot of sense - using UTC will avoid all the endless issues with DST.

However, I was very confused by this behaviour until I found this PR with @circlingthesun's example! The documentation definitely needs updating with a prominent notice to explain this.

I would also like to express my appreciation for all your hard work in maintaining this! :)

**Pull request merged**
