### PR TITLE
allow ability to provide timezone support via custom Date class

### PR DESCRIPTION
**Pull request by mattcasey**
Integration was inspired by @chotiwat. I wanted to use moment-timezone, so this patch allows anyone to write a plugin to override the Date object used internally by rrule. My fork also includes a new rrule option "timezone"

Next steps: Tests? Also, I would like to include my moment-timezone plugin as part of the rrule library, would be happy to hear suggestions where/how a plugin system should be done. Currently, I'm implementing moment-timezone like this:

```
var rrule = require('rrule');
var RRule = rrule.RRule;

var moment = require('moment-timezone');

// takes timezone str as last parameter, just like js-timezone
function momentDate() {
    var args = Array.prototype.slice.call(arguments);
    var tz;
    if (args.length > 1 && typeof args[args.length - 1] === 'string') {
        // last argument is timezone
        tz = args.pop();
    }
    if (args.length === 1) {
        args = new Date(args[0]);
    }
    this._moment = moment.tz(args, tz);
}

momentDate.prototype.getDate = function () {
    return this._moment.date();
};

momentDate.prototype.getDay = function () {
    return this._moment.day();
};

momentDate.prototype.getFullYear = function () {
    return this._moment.toDate().getFullYear();
};

momentDate.prototype.getHours = function () {
    return this._moment.hours();
};

momentDate.prototype.getMinutes = function () {
    return this._moment.minutes();
};

momentDate.prototype.getMonth = function () {
    return this._moment.month();
};

momentDate.prototype.getSeconds = function () {
    return this._moment.seconds();
};

momentDate.prototype.getTime = function () {
    return this._moment.toDate().getTime();
};

momentDate.prototype.getTimezoneOffset = function () {
    return this._moment.zone();
};

momentDate.prototype.setMilliseconds = function (ms) {
    this._moment.milliseconds(ms);
};

momentDate.prototype.toString = function () {
    return this._moment.toString();
};

momentDate.prototype.valueOf = function () {
    return this._moment.toDate().getTime();
};

rrule.setDateClass(momentDate);
```

### CODE REVIEW

**Comment by aramk** [comment]
@mattcasey in case you're still interested in this, I've created #97 to implement this with tests across the whole library. Thanks for pointing me in the right direction!

**Comment by arolson101** [comment]
Hi!  I'm trying to clear out bugs and PRs.  If this PR is still wanted/relevant, please comment and/or fix the conflicts!

**Comment by jimmywarting** [comment]
need timezones as well

**Comment by davidgoli** [comment]
This will be addressed in a new PR.

**Pull request closed without merging**
