### PR TITLE
Time Zone Support

### PR DESCRIPTION
**Pull request by aramk**
This uses some of the methods in #78 and is an implementation of what was discussed in #38.

I've created a separate library at [tz-date](https://github.com/aramk/tz-date) which contains a `TimeZoneDate` that extends `Date`, adheres to its API, has Mocha tests, and supports time zones through http://momentjs.com/timezone. This is in CoffeeScript so you'll need to run `bower install` in rrule and then `grunt build` in `bower_components/tz-date` to generate the JavaScript used by the tests I've added.

Since Date doesn't support having a time zone as the last argument and returns Invalid Date, I've
created a new method called `createDate()` to handle this situation. All date creation in the
library is now handled through this method. This also adds a "timezone" option which is passed to
all calls of `createDate()`.

As for the testing, tests/index.html will still work as before and use Date. In tests/timezone.html
I add TimeZoneDate and its dependency libraries, and in timezone-tests I set TimeZoneDate as the
custom Date class to use. Here I've tests two time zones - my home city of Melbourne and
Los Angeles. TimeZoneDate has its own Mocha [tests](https://github.com/aramk/tz-date/blob/master/test/TimeZoneDateSpec.coffee) to ensure the getters and setters behave correctly.
For maximum coverage I've also ensured the existing tests are run with TimeZoneDate, so I'm fairly
convinced it's working well :)

One thing we might want to standardise is whether to use `timeZone` or `timezone`. I've been using
the "time zone" convention on the Wikipedia page, but "timezone" is fairly common elsewhere,
especially in libraries, and moment-timezone's docs use it interchangeably... Not sure which is
"correct", but standardising will reduce the confusion.

I hope this can be merged since it adds a vital feature which is missing from this library and which
likely impacts many people who are building apps and deploying them across the world. If not, this
branch is here for everyone to use.

### CODE REVIEW

**Comment by fampinheiro** [comment]
Any updates regarding this?

**Comment by aramk** [comment]
I've been using this in production and it's been working fine. I've added tests, it's just a question of whether this is eventually merged in or not.

**Comment by jamesdixon** [comment]
@aramk I'm going to give your fork a shot. I see there a specific branch that is more up-to-date than others? I see one with `stable` appended to the name, so was curious.

Thanks!

**Comment by aramk** [comment]
@jamesdixon Yeah the `feature/timezone-stable` is older and the timezone branch is based off that. I'm using `feature/meteor` which has a few other fixes actually.

**Comment by aramk** [comment]
Removed feature/timezone-stable to avoid confusion

**Comment by jamesdixon** [comment]
Thanks @aramk! Going to give it a shot. Is there a good place in the repo to grab an example?

**Comment by jamesdixon** [comment]
Nevermind, I see the tests. Thanks!

**Comment by aramk** [comment]
Yeah, see
https://github.com/aramk/rrule/blob/feature/meteor/tests/timezone-tests.js

**Comment by Sutikshan** [comment]
Thanks @aramk , I am trying to use your fork in production for our purpose. There are few obstacle I am facing -
- I am not able to run tests cases, when I try $grunt test, it is failing with error 
Error: Cannot find module 'tz-date'
Though tz-date is present inside node_modules folder. any clue?
- When I try to use it in our project as following, it get stuck inside infinite loop of _iter function
`new Rrule(interval).after("FREQ=WEEKLY;BYDAY=FR;BYHOUR=15;BYMINUTE=0;TIMEZONE=Australia/Perth")`

Is Dtstart/until are mandatory attribute, if we use your fix?

**Comment by aramk** [comment]
@Sutikshan I think `dtstart` is mandatory so we have a starting date for the recurrence, and if you don't provide an `until` it will run endlessly?

**Comment by arolson101** [comment]
Hi!  I'm trying to clear out bugs and PRs.  If this PR is still wanted/relevant, please comment and/or fix the conflicts!

**Comment by davidgoli** [comment]
This will be addressed in a separate PR.

**Pull request closed without merging**
