### PR TITLE
Make it work with date before 1970

### PR DESCRIPTION
**Pull request by bubbatls**
The Math.abs was the cause of the weird behavior

### CODE REVIEW

**Comment by arolson101** [comment]
Can you explain why Math.abs was wrong?

**Comment by bubbatls** [comment]
because the lib needs a signed delta not an unsigned one.

**Comment by arolson101** [comment]
Sorry, I don't know the code that well.
Would you mind adding a test to your PR?

**Comment by bubbatls** [comment]
I see the test folder but I dont' understand how to execute them (I use chrome) so I will not add a test without testing it.

**Comment by arolson101** [comment]
The tests are run via command-line- clone the repo, run ```npm install```, then ```npm test```
If you want you can just reply with an example of it failing I will write the test.

**Comment by bubbatls** [comment]
I've made a pull request with a test that should work but don't without the current fix

**Comment by arolson101** [comment]
Thank you!

**Pull request merged**
