### PR TITLE
fix #321

### LINKED ISSUE #321: RRule accepts "NaN" as a valid interval and causes infinite loop
The problem arises when a `NaN` value is supplied to the interval and creates `INTERVAL=NaN`.  This happened when coercion was attempted on a non-integer value, and created `NaN` instead.
### Steps to reproduce
```es6
import RRule from 'rrule';

const rrule = new RRule({
  freq: RRule.WEEKLY,
  interval: NaN,
  byweekday: [RRule.MO, RRule.FR],
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2012, 12, 31))
})

// DTSTART:20120201T103000Z\nRRULE:FREQ=WEEKLY;INTERVAL=NaN;BYDAY=MO,FR;UNTIL=20130131T000000Z
console.log(rrule.toString());
```
### Actual Results
```
DTSTART:20120201T103000Z\nRRULE:FREQ=WEEKLY;INTERVAL=NaN;BYDAY=MO,FR;UNTIL=20130131T000000Z
```
### Expected Results
```
DTSTART:20120201T103000Z\nRRULE:FREQ=WEEKLY;BYDAY=MO,FR;UNTIL=20130131T000000Z
```
### Additional info
```
macOS Mojave v10.14.2

$ date
Mon 11 Feb 2019 16:50:44 GMT

$ node --version
v8.15.0

rrule version
2.6.0
```

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x] Expected output
- [x] Actual output
- [x] The version of `rrule` you are using
- [x] Your operating system
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

### PR DESCRIPTION
**Pull request by yitomok**
---

### Thanks for contributing to `rrule`!

To submit a pull request, please verify that you have done the following:

- [X] Merged in or rebased on the latest `master` commit
- [X] Linked to an existing bug or issue describing the bug or feature you're
      addressing
- [x] Written one or more tests showing that your change works as advertised

### CODE REVIEW

**Comment by yitomok** [comment]
Check type on `interval`. I don't agree to return default, in fact it should throw an error on invalid value

**Comment by davidgoli** [comment]
Thanks for contributing! This change seems sensible enough, but please write a test demonstrating the fix. Thank you!

**Comment by yitomok** [comment]
@davidgoli let see if that's enough 😃

**Comment by davidgoli** [comment]
@yitomok Please re-submit this work; your test did not pass and I had to revert the merge. Sorry about that!

**Pull request merged**
